title: artistic # this is your title
author:
  name: Emre Kayık
  company:
    name: StudioEK
    role: Developer
    url: https://github.com/studioek
  email: emrekayik1905@gmail.com

#lang: ""  # web site lang

# google_analytics:

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

theme: artistic

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# paginate settings
paginate: 5
paginate_path: "/page:num/"


artistic:
  social_links:
    - { platform: devto,          user_url: "https://dev.to/emrekayik" }
    #- { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    #- { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    #- { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/studioek/artistic" }
    #- { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/studioek0" }
    #- { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    #- { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    #- { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    - { platform: telegram,       user_url: "https://t.me/emrekayik" }
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
    - { platform: rss,            user_url: "https://studioek.github.io/artistic/feed.xml" }